jQuery("p.disablewithjavascript").css({display:"none"});var scrollback_messages=jQuery("table.contribution.scrollback");var post_element=jQuery("article.post")[0];function start_torches(torches){jQuery(torches).each(function(){this.frame=1;this.ill=0.2;this.hide=false;});jQuery(window).scroll();function continue_torches(){var cont=false;jQuery(torches).each(function(){if(this.frame<6){this.frame+=1;this.ill=this.frame*0.1;cont=true;}else if(this.frame>=6&&this.frame<=8){var new_frame=Math.floor(Math.random()*2)+6;if(new_frame>=this.frame){this.frame=new_frame+1;}else{this.frame=new_frame;}
this.ill=Math.random()*0.3+0.45;cont=true;}else if(this.frame>8&&this.frame<12){this.frame=this.frame+=1;this.ill=(14-this.frame)*0.1;cont=true;}else{this.frame=0;this.ill=0;}});jQuery(window).scroll();if(cont){setTimeout(continue_torches,100);}}
setTimeout(continue_torches,100);}
function end_torches(torches){jQuery(torches).each(function(){this.frame=this.loop_end+1;});}
function start_final_torches(torches){jQuery(torches).each(function(){this.frame=1;this.ill=0.2;this.hide=false;});jQuery(window).scroll();function continue_torches(){var cont=false;jQuery(torches).each(function(){if(this.frame<10){this.frame+=1;this.ill=this.frame*0.1;cont=true;}else if(this.frame>=10&&this.frame<=12){var new_frame=Math.floor(Math.random()*2)+10;if(new_frame>=this.frame){this.frame=new_frame+1;}else{this.frame=new_frame;}
this.ill=Math.random()*0.3+0.7;cont=true;}else if(this.frame>12&&this.frame<13){this.frame=this.frame+=1;this.ill=(14-this.frame)*0.1;cont=true;}else{this.frame=0;this.ill=0;}});jQuery(window).scroll();if(cont){setTimeout(continue_torches,100);}}
setTimeout(continue_torches,100);}
function start_flicker_shadow(shadow){function flicker(){shadow.hide=false;var scale=1.025-Math.random()*0.05;var vskew=Math.random()*0.3-0.15;var transform_str="scale("+scale.toFixed(4)+") skewX("+vskew.toFixed(2)+"deg)";jQuery("#shadowinner").css({"transform":transform_str,"-webkit-transform":transform_str,"-ms-transform":transform_str,"-moz-transform":transform_str,"-o-transform":transform_str,});setTimeout(flicker,100);}
setTimeout(flicker,100);}
var kat={id:"kat",x:438,y:-5,z:100,ill:0.9,frame:"normal",subimage:"justkat",framex:true,frames:{normal:0,r0:135*1,r1:135*1,r2:135*2,r3:135*2,r4:135*2,r5:135*2,r6:135*2,r7:135*3,r8:135*3,r9:135*4,l0:135*5,l1:135*5,l2:135*6,l3:135*6,l4:135*6,l5:135*6,l6:135*6,l7:135*7,l8:135*7,l9:135*8,turn:135*9,huh:135*10,sad:135*11,w0:135*12,w1:135*13,w2:135*14,w3:135*15,w4:135*16,w5:135*17,w6:135*18,w7:135*19,w8:135*20,w9:135*21,w10:135*22,w11:135*23,w12:135*24,w13:135*25,w14:135*26,w15:135*27}};var katia_walking_frames=[{timing:1500,step_offset_x:0,frame:"normal"},{timing:1500,step_offset_x:0,frame:"w0"},{timing:50,step_offset_x:10,frame:"w6"},{timing:50,step_offset_x:20,frame:"w7"},{timing:50,step_offset_x:30,frame:"w8"},{timing:50,step_offset_x:40,frame:"w9"},{timing:1000,step_offset_x:50,frame:"w10"},{timing:50,step_offset_x:60,frame:"w1"},{timing:50,step_offset_x:70,frame:"w2"},{timing:50,step_offset_x:80,frame:"w3"},{timing:50,step_offset_x:90,frame:"w4"},{timing:1000,step_offset_x:100,frame:"w5"},{timing:50,step_offset_x:110,frame:"w6"},{timing:50,step_offset_x:120,frame:"w7"},{timing:50,step_offset_x:130,frame:"w8"},{timing:50,step_offset_x:140,frame:"w9"},{timing:1000,step_offset_x:150,frame:"w10"},{timing:50,step_offset_x:160,frame:"w1"},{timing:50,step_offset_x:170,frame:"w2"},{timing:50,step_offset_x:180,frame:"w3"},{timing:50,step_offset_x:190,frame:"w4"},{timing:1000,step_offset_x:200,frame:"w5"},{timing:50,step_offset_x:210,frame:"w6"},{timing:50,step_offset_x:220,frame:"w7"},{timing:50,step_offset_x:230,frame:"w8"},{timing:50,step_offset_x:240,frame:"w9"},{timing:1000,step_offset_x:250,frame:"w10"},{timing:100,step_offset_x:250,frame:"w11"},{timing:100,step_offset_x:250,frame:"w12"},{timing:1000,step_offset_x:250,frame:"w13"},{timing:100,step_offset_x:250,frame:"w14"},{timing:1000,step_offset_x:250,frame:"w15"},]
var katspire={id:"katspire",x:46,y:-600,z:50,scalef:1.375,step_offset_x:330};var endroom={id:"endroom",x:65,y:7640,z:4900,scalef:1.0,step_offset_x:410,step_offset_y:235,clippingbox:"clippingbox",clippingimg:"clippingimg"}
var step_offsets=[305,330,359,389,418,421,404,367,312,275,254,262];var katshine={id:"katshine",x:0,y:0,z:endroom.z,hide:true,ill:0.01}
var steps=[];for(var i=1;i<=48;i++){steps.push({id:"step"+i.toString(),x:162,y:i*160,z:i*100,step_offset_x:step_offsets[i%12],step_offset_y:35,bounceable:true})}
var kat_steps=steps.concat([endroom,endroom]);var mattes=[{id:"step46matte",x:162,y:7360,z:4600,ill:0.01},{id:"step47matte",x:162,y:7520,z:4700,ill:0.01},{id:"step48matte",x:162,y:7680,z:4800,ill:0.01}];steps[45].matte=mattes[0];steps[46].matte=mattes[1];steps[47].matte=mattes[2];function torches_on_event(torches){var tt=torches;function torches_on(){start_torches(tt);}
return torches_on;}
function torches_off_event(torches){var tt=torches;function torches_off(){end_torches(tt);}
return torches_off;}
horrors=[{id:"horror1",subimage:"horror1i",width:40,height:338,onright:true,numframes:22},{id:"horror2",subimage:"horror2i",width:46,height:279,onright:false,numframes:22},{id:"horror3",subimage:"horror3i",width:100,height:330,onright:true,numframes:22},]
function horror_start(horror){var anim_start=new Date();var frame=0;function horror_play(){var post_offset=jQuery(post_element).offset();var post_width=jQuery(post_element).outerWidth();if(frame>=horror.numframes){jQuery(document.getElementById(horror.id)).css({visibility:"hidden"});return;}
var left;if(horror.onright){left=post_offset.left+post_width-2;}else{left=post_offset.left-horror.width+2;}
jQuery(document.getElementById(horror.id)).css({visibility:"visible",left:left,top:200})
jQuery(document.getElementById(horror.subimage)).css({left:-frame*horror.width})
frame++;setTimeout(horror_play,50);}
setTimeout(horror_play,0);}
function horror_event(horror){var h=horror;function horror_start_fn(){horror_start(h);}
return horror_start_fn;}
var torchframes={0:0,1:143,2:286,3:429,4:572,5:715,6:858,7:1001,8:1144,9:1287,10:1430,11:1573,12:1716};var torches=[{id:"torch1a",x:22,y:407,z:400,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch1ap",frames:torchframes,hide:true},{id:"torch1b",x:871,y:407,z:400,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch1bp",frames:torchframes,hide:true},{id:"torch2a",x:-5,y:1687,z:1200,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch2ap",frames:torchframes,hide:true},{id:"torch2b",x:744,y:1687,z:1200,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch2bp",frames:torchframes,hide:true},{id:"torch3a",x:0,y:2967,z:2000,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch3ap",frames:torchframes,hide:true},{id:"torch3b",x:849,y:2967,z:2000,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch3bp",frames:torchframes,hide:true},{id:"torch4a",x:22,y:4247,z:2800,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch4ap",frames:torchframes,hide:true},{id:"torch4b",x:871,y:4247,z:2800,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch4bp",frames:torchframes,hide:true},{id:"torch5a",x:-5,y:5527,z:3600,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch5ap",frames:torchframes,hide:true},{id:"torch5b",x:744,y:5527,z:3600,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch5bp",frames:torchframes,hide:true},{id:"torch6a",x:0,y:6807,z:4400,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch6ap",frames:torchframes,hide:true},{id:"torch6b",x:849,y:6807,z:4400,loop_start:6,loop_end:8,ill:0,flame_ill:0.5,flame_variance:0.3,frame:0,subimage:"torch6bp",frames:torchframes,hide:true}];var final_torch_frames={0:0,1:96,2:192,3:288,4:384,5:480,6:576,7:672,8:768,9:864,10:960,11:1056,12:1152};var final_torch={id:"torchf",x:796,y:7629,z:4900,loop_start:10,loop_end:12,ill:0,flame_ill:0.7,flame_variance:0.4,frame:0,subimage:"torchfp",frames:final_torch_frames,hide:true};for(var i=0;i<6;i++){steps[i*8+3].events=[torches_on_event([torches[i*2],torches[i*2+1]])];steps[i*8+7].events=[torches_off_event([torches[i*2],torches[i*2+1]])];}
steps[13].events=[horror_event(horrors[0])];steps[29].events=[horror_event(horrors[1])];steps[37].events=[horror_event(horrors[2])];var shadow={id:"shadow",x:295,y:7845,z:4900,ill:0.01,opacity:0.6,hide:true};var lights=[kat,final_torch].concat(torches);var everything=[katspire,kat,endroom,final_torch,shadow,katshine].concat(steps,torches,mattes);var eyeball_x=500;var eyeball_y_perc=60;var eyeball_y_max_from_bottom=300;var camera_offset_x=500;var camera_x=500;var camera_offset_y=0;var unity_z_distance=400;var focus_length_z=500;var camera_offset_z=500;var z_cutoff=50;var camera_limit_z=5300;var distance_opacity=0.001;var kat_step=0;var katia_moving=false;var katia_walking=false;var katia_walking_frame=0;var katia_foot="r";var target_step=0;var katia_step_offset_x=-63;var katia_step_offset_y=-200;var hop_y=100;var step_offset_x=339;var step_offset_y=35;var bounce_on=[5,10,5,0,5];var bounce_off=[10,5,0,-5,0];var bounce_through=[5,5,0,-5,0];var bounce_ms_per_frame=40;var illumination_fade=0.002;var illumination_cutoff=0.1;var scroll_to_z_factor=0.625;var camera_limit_y=(camera_limit_z-camera_offset_z)/scroll_to_z_factor+camera_offset_y;var camera_low_limit_y=(100-camera_offset_z)/scroll_to_z_factor+camera_offset_y;camera_low_limit_y=400;var anim_frame=20;var pause_frame=200;var fast_step_time=400;var slow_step_time=500;var current_step_time=500;var min_camera_z_from_kat=500;var stwiggle_period=5000;var stwiggle_ampl=50;var stwiggle_length=9;var stwiggle_anim_period=40;var first_full_step=4;var last_full_step=43;var decrease_factor_per_step=0.2;var minimum_z_for_scrollback=800;var scrollback_z=0;var previous_scrollback_z=0;var camera_tangent=-5;var rollback_mode=false;function start_stwiggles(){var anim_start=new Date();function animate(){var phase=(new Date()-anim_start)/stwiggle_period;jQuery(steps).each(function(index){var prev_x=this.x;var ampl=stwiggle_ampl;if(this.pre_wiggle_x==undefined){this.pre_wiggle_x=this.x;}
if(index<first_full_step){ampl=stwiggle_ampl*(1-decrease_factor_per_step*(first_full_step-index));}else if(index>last_full_step){ampl=stwiggle_ampl*(1-decrease_factor_per_step*(index-last_full_step));}
this.x=this.pre_wiggle_x+Math.floor(Math.sin(Math.PI*(phase+(index/stwiggle_length)))*ampl);if(this.matte!=undefined){this.matte.x=this.x;}
if(this.id==kat_steps[kat_step].id){kat.x+=this.x-prev_x;}});setTimeout(animate,stwiggle_anim_period);jQuery(window).scroll();}
setTimeout(animate,0);}
function start_vary_stwiggles(){var anim_start=new Date();var orig_stwiggle_period=stwiggle_period;var orig_stwiggle_ampl=stwiggle_ampl;var orig_stwiggle_anim_period=stwiggle_anim_period;var orig_decrease_factor_per_step=decrease_factor_per_step;function animate(){var ticks=new Date-anim_start;var progress=ticks/2000;var progress=1.01-Math.pow(2,-ticks/1000);if(progress>1){stwiggle_anim_period=orig_stwiggle_anim_period;}else{stwiggle_anim_period=20;}
stwiggle_period=(1-progress)*2000+progress*orig_stwiggle_period;stwiggle_ampl=(1-progress)*50+progress*orig_stwiggle_ampl;decrease_factor_per_step=progress*orig_decrease_factor_per_step;if(progress<1){setTimeout(animate,anim_frame);}}
setTimeout(animate,0);}
function start_katshine(katshine){function shine(){katshine.opacity=Math.random()*0.15;setTimeout(shine,100);}
setTimeout(shine,0);}
var scrollback_message_counter=0;var frame_after_turn="normal";function activate_scrollback_message(){var tallbox_offset=jQuery("#tallbox").offset();var scrolltop=jQuery(window).scrollTop();var the_message=scrollback_messages[scrollback_message_counter%scrollback_messages.length];jQuery(the_message).css({display:"table",visibility:"hidden",top:0});var outerheight=jQuery(the_message).outerHeight();jQuery(the_message).css({visibility:"visible",top:scrolltop-tallbox_offset.top-outerheight-100});frame_after_turn=jQuery(the_message).attr("pframe");scrollback_message_counter++;rollback_mode=true;}
function redraw_world(){var tallbox_offset=jQuery("#tallbox").offset();var post_offset=jQuery(post_element).offset();var post_width=jQuery(post_element).outerWidth();var window_height=jQuery(window).height();var scrolltop=jQuery(window).scrollTop()
eyeball_x=post_offset.left+post_width/2;var camera_tangent_factor=Math.tan(camera_tangent/180*Math.PI);if(post_width<865){focus_length_z=post_width/865*unity_z_distance;}else{focus_length_z=unity_z_distance;}
var scrolly=scrolltop-tallbox_offset.top-100;var camera_z=camera_offset_z+scrolly*scroll_to_z_factor;var z_limit_text="";if(camera_z>camera_limit_z){camera_z=camera_limit_z;}else if(camera_z<kat.z+min_camera_z_from_kat){scrollback_z=kat.z+min_camera_z_from_kat-camera_z;camera_z=kat.z+min_camera_z_from_kat;if(camera_z>camera_limit_z){camera_z=camera_limit_z}else{z_limit_text=" *";}}else{scrollback_z=0;}
var camera_y=camera_offset_y+scrolly;var effective_eyeball_y=Math.floor(Math.max(window_height*eyeball_y_perc/100,window_height-(eyeball_y_max_from_bottom*focus_length_z/unity_z_distance)));if(camera_y<camera_low_limit_y){effective_eyeball_y=effective_eyeball_y+camera_low_limit_y-camera_y;camera_y=camera_low_limit_y;}
if(camera_y>camera_limit_y){effective_eyeball_y=effective_eyeball_y+camera_limit_y-camera_y;camera_y=camera_limit_y}
function adjust(index){var delta_z=camera_z-this.z;var opacity_ref_z=this.z;if(delta_z<z_cutoff||this.hide==true){jQuery(document.getElementById(this.id)).css({visibility:"hidden"});}else{var opacity=0;if(this.ill>0){if(this.opacity==undefined){opacity=1.0;}else{opacity=this.opacity;}}else{var darkness=1.0;jQuery(lights).each(function(index){darkness*=(1-Math.max(this.ill-Math.abs(opacity_ref_z-this.z)*illumination_fade,0));});opacity=1-darkness;}
if(opacity<illumination_cutoff){jQuery(document.getElementById(this.id)).css({visibility:"hidden"});}else{var scale=focus_length_z/delta_z;var left=Math.floor((this.x-camera_x)*scale+eyeball_x);var top=Math.floor((this.y-camera_y)*scale+camera_tangent_factor*delta_z+effective_eyeball_y);if(this.scalef!=undefined){scale=scale*this.scalef;}
var transform_str="scale("+scale.toFixed(4)+")";if(this.vskew!=undefined){transform_str+=" skew("+this.vskew.toFixed(2)+"deg)";}
jQuery(document.getElementById(this.id)).css({visibility:"visible",top:top,left:left,"transform":transform_str,"-webkit-transform":transform_str,"-ms-transform":transform_str,"-moz-transform":transform_str,"-o-transform":transform_str,opacity:opacity.toFixed(2)});if(this.frame!=undefined){if(this.framex==true){jQuery(document.getElementById(this.subimage)).css({left:-this.frames[this.frame]});}else{jQuery(document.getElementById(this.subimage)).css({top:-this.frames[this.frame]});}}
if(this.clippingbox!=undefined){var this_width=jQuery(document.getElementById(this.id)).outerWidth()*scale;var combined_margins=Math.floor(this_width-post_width);if(combined_margins<0){combined_margins=0;}
var right_margin=Math.floor(combined_margins/2);var left_margin=combined_margins-right_margin;jQuery(document.getElementById(this.clippingbox)).css({"margin-right":right_margin,"margin-left":left_margin})
jQuery(document.getElementById(this.clippingimg)).css({left:-left_margin});}}}}
jQuery(everything).each(adjust);if(camera_z==camera_limit_z){target_step=48;}else if(camera_z-kat_steps[kat_step].z>min_camera_z_from_kat+200){target_step=kat_step+2;}else if(camera_z-kat_steps[kat_step].z>min_camera_z_from_kat+100){target_step=kat_step+1;}
if(target_step>48){target_step=48;}}
jQuery(window).bind('scroll',redraw_world).bind('touchmove',redraw_world).trigger('scroll');function bounce_step(step,bounce_arr){if(step.bounceable!=true){return;}
var start_anim=new Date();var step=step;if(step.pre_bounce_y==undefined){step.pre_bounce_y=step.y;}
function bouncing(){var ticks=new Date()-start_anim;var frame=Math.floor(ticks/bounce_ms_per_frame);var bounce_y=bounce_arr[frame];if(bounce_y!=undefined){step.y=step.pre_bounce_y+bounce_y;setTimeout(bouncing,anim_frame);jQuery(window).scroll();}}
setTimeout(bouncing,0);}
var start_anim;var frame_ticks_start;var step_origin_x;var step_origin_y;var step_origin_z;var step_target_x;var step_target_y;var step_target_z;var para_a;var para_b;function anim_katia(){var stepped_on=false;var stepped_off=false;var prev_kat_step=kat_step;if(katia_moving){var ticks=new Date()-start_anim;var step_fraction=ticks/current_step_time;if(step_fraction>=1.0){kat.x=step_target_x;kat.y=step_target_y;kat.z=step_target_z;kat.frame="normal";katia_moving=false;stepped_on=true;if(kat_steps[kat_step].events!=undefined){jQuery(kat_steps[kat_step].events).each(function(index){this();});}}else{kat.x=step_origin_x*(1-step_fraction)+step_target_x*step_fraction;kat.y=step_origin_y+para_a*Math.pow(step_fraction,2)+para_b*step_fraction;kat.z=step_origin_z*(1-step_fraction)+step_target_z*step_fraction;kat.frame=katia_foot+Math.floor(step_fraction*10);}}
if(!katia_moving&&target_step>kat_step){start_anim=new Date();step_origin_x=kat.x;step_origin_y=kat.y;step_origin_z=kat.z;step_target_x=kat_steps[kat_step+1].x+kat_steps[kat_step+1].step_offset_x+katia_step_offset_x;step_target_y=kat_steps[kat_step+1].y+kat_steps[kat_step+1].step_offset_y+katia_step_offset_y;step_target_z=kat_steps[kat_step+1].z
para_a=Math.abs(step_target_y-step_origin_y)*2-hop_y;para_b=step_target_y-step_origin_y-para_a;if(target_step>kat_step+1){current_step_time=fast_step_time;}else{current_step_time=slow_step_time;}
kat_step+=1;katia_moving=true;stepped_off=true;if(stepped_on&&katia_foot=="r"){katia_foot="l";}else{katia_foot="r";}}
if(!katia_moving&&!stepped_on&&!rollback_mode&&previous_scrollback_z<=0&&scrollback_z>0&&kat_step>5&&kat_step<47){rollback_mode=true;activate_scrollback_message();}
previous_scrollback_z=scrollback_z;if(stepped_off&&rollback_mode){jQuery(scrollback_messages).css({visibility:"hidden",display:"none"});rollback_mode=false;}
if(!katia_moving&&!stepped_on&&rollback_mode){if(scrollback_z>50){kat.frame="turn";}else if(kat.frame=="turn"&&scrollback_z>=0){kat.frame=frame_after_turn;}}
if(stepped_on&&stepped_off){bounce_step(kat_steps[prev_kat_step],bounce_through);}else if(stepped_on){bounce_step(kat_steps[prev_kat_step],bounce_on);}else if(stepped_off){bounce_step(kat_steps[prev_kat_step],bounce_off);}
if(!katia_moving&&kat_step==48){if(katia_walking){var wf=katia_walking_frames[katia_walking_frame];var ticks=new Date()-start_anim;if(ticks-frame_ticks_start>wf.timing){frame_ticks_start+=wf.timing;katia_walking_frame++;if(katia_walking_frame==30){start_final_torches([final_torch]);shadow.hide=false;start_flicker_shadow(shadow);start_vary_stwiggles();katshine.x=kat.x;katshine.y=kat.y;katshine.z=kat.z;katshine.hide=false;start_katshine(katshine);}}
if(katia_walking_frame>=katia_walking_frames.length){katia_walking=false;kat_step=49;}else{wf=katia_walking_frames[katia_walking_frame];kat.x=endroom.step_offset_x+wf.step_offset_x;kat.frame=wf.frame;}}else{start_anim=new Date();frame_ticks_start=0;katia_walking=true;katia_walking_frame=0;}}
jQuery(window).scroll();if(katia_moving||katia_walking){setTimeout(anim_katia,anim_frame);}else{setTimeout(anim_katia,pause_frame);}}
jQuery(anim_katia);jQuery(start_stwiggles);